version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    container_name: apiology-web-container
    restart: always
    volumes:
      - ./api/:/var/www/html/
    ports:
      - 80:80
